version: '3'
services:
  server-container:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - mysql-container

  mysql-container:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: YCABtPLrKbCk
      MYSQL_DATABASE: solvdLawDB
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3307:3306"