version: '3'

services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 8089:3001

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: YCABtPLrKbCk
      MYSQL_DATABASE: solvdLawDB
    ports:
      - "3307:3307"