-- MySQL Script generated by MySQL Workbench
-- Thu Oct 19 16:53:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema solvdLawDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema solvdLawDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `solvdLawDB` DEFAULT CHARACTER SET utf8 ;
USE `solvdLawDB` ;

-- -----------------------------------------------------
-- Table `solvdLawDB`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solvdLawDB`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
