CREATE SCHEMA IF NOT EXISTS `solvdLawDB` DEFAULT CHARACTER SET utf8 ;

USE `solvdLawDB` ;

CREATE TABLE IF NOT EXISTS `user` (
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`username`)
) ENGINE = InnoDB;