name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Docker
        uses: docker/setup-buildx-action

      - name: Login to Docker Hub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin


      - name: Dependencies
        run: npm install

      - name: Lint
        run: npm run lint
          
      - name: Test
        run: npm test

      # - name: Deploy
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   run: ssh root@localhost 'cd /backend/server && git pull origin main && npm install && pm2 restart backend'
