name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag avoitovich/backend-server-container:latest:$(date +%s)
      working-directory: backend

    # - name: Build the Docker DB image
    #   run: docker build . --file Dockerfile --tag backend-server-container:$(date +%s)
    #   working-directory: backend

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install
      working-directory: backend

    - name: Lint
      run: npm run lint
      working-directory: backend
        
    - name: Test
      run: npm test
      working-directory: backend
